export const POKEMON_NATURES = [
    { value: "-1", label: "指定なし" },
    { value: "0", label: "がんばりや" },
    { value: "1", label: "さみしがり" },
    { value: "2", label: "ゆうかん" },
    { value: "3", label: "いじっぱり" },
    { value: "4", label: "やんちゃ" },
    { value: "5", label: "ずぶとい" },
    { value: "6", label: "すなお" },
    { value: "7", label: "のんき" },
    { value: "8", label: "わんぱく" },
    { value: "9", label: "のうてんき" },
    { value: "10", label: "おくびょう" },
    { value: "11", label: "せっかち" },
    { value: "12", label: "まじめ" },
    { value: "13", label: "ようき" },
    { value: "14", label: "むじゃき" },
    { value: "15", label: "ひかえめ" },
    { value: "16", label: "おっとり" },
    { value: "17", label: "れいせい" },
    { value: "18", label: "てれや" },
    { value: "19", label: "うっかりや" },
    { value: "20", label: "おだやか" },
    { value: "21", label: "おとなしい" },
    { value: "22", label: "なまいき" },
    { value: "23", label: "しんちょう" },
    { value: "24", label: "きまぐれ" },
];
